name: "PrdApply"

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  #    - reopened
  # workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_CLOUD_ORGANIZATION: "${{vars.TF_CLOUD_ORGANIZATION}}"


jobs:

  apply:
    name: apply on pull request merge to main branch
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    env:
      DeployEnv: prd

    # Use the Bash shell regardless of GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: set environment variables
        run: |
          echo "TF_WORKSPACE=${{github.event.repository.name}}-$DeployEnv" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -upgrade

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -var-file $DeployEnv.tfvars
        continue-on-error: true

      - name: Terraform Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1

      - name: Create Issue on Failed workflow on apply
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action workflow failed.
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
          assignees: ash-dey-sa
